// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package declarative defines the schema for the gcloud declarative YAML
// command files emitted by the surfer.
package declarative

//go:generate go run -tags configdocgen ../../../../cmd/config_doc_generate.go -input . -output ../../../../doc/gcloud/gcloud-declarative-schema.md -root Command -root-title Command -title "gcloud Declarative YAML"

// Command represents a single gcloud declarative YAML command definition.
type Command struct {
	ReleaseTracks []string      `yaml:"release_tracks,omitempty"`
	AutoGenerated bool          `yaml:"auto_generated,omitempty"`
	Hidden        bool          `yaml:"hidden,omitempty"`
	HelpText      HelpText      `yaml:"help_text"`
	Arguments     Arguments     `yaml:"arguments"`
	Request       *Request      `yaml:"request,omitempty"`
	Async         *Async        `yaml:"async,omitempty"`
	Response      *Response     `yaml:"response,omitempty"`
	Update        *UpdateConfig `yaml:"update,omitempty"`
	Output        *OutputConfig `yaml:"output,omitempty"`
}

// UpdateConfig describes how update commands handle field masks.
type UpdateConfig struct {
	ReadModifyUpdate     bool `yaml:"read_modify_update"`
	DisableAutoFieldMask bool `yaml:"disable_auto_field_mask,omitempty"`
}

// OutputConfig describes how command output should be formatted.
type OutputConfig struct {
	Format string `yaml:"format,omitempty"`
}

// Response describes how to interpret the response of a command.
type Response struct {
	IDField string `yaml:"id_field,omitempty"`
}

// HelpText describes the help text for a command.
type HelpText struct {
	Brief       string `yaml:"brief"`
	Description string `yaml:"description"`
	Examples    string `yaml:"examples,omitempty"`
}

// Default represents an optional default value for an argument.
type Default struct {
	Value *any
}

// IsZero reports whether d holds no value.
func (d Default) IsZero() bool {
	return d.Value == nil
}

// MarshalYAML implements yaml.Marshaler so that the underlying value is
// emitted directly when present.
func (d Default) MarshalYAML() (any, error) {
	if d.Value == nil {
		return nil, nil
	}
	return *d.Value, nil
}

// Arguments contains the argument definitions for a command.
type Arguments struct {
	Params []Argument `yaml:"params,omitempty"`
}

// Argument describes a single command argument.
type Argument struct {
	ArgName              string            `yaml:"arg_name,omitempty"`
	APIField             string            `yaml:"api_field,omitempty"`
	HelpText             string            `yaml:"help_text"`
	Action               string            `yaml:"action,omitempty"`
	IsPositional         bool              `yaml:"is_positional"`
	IsPrimaryResource    bool              `yaml:"is_primary_resource,omitempty"`
	RequestIDField       string            `yaml:"request_id_field,omitempty"`
	ResourceSpec         *ResourceSpec     `yaml:"resource_spec,omitempty"`
	Required             bool              `yaml:"required"`
	Repeated             bool              `yaml:"repeated,omitempty"`
	Clearable            bool              `yaml:"clearable,omitempty"`
	Type                 string            `yaml:"type,omitempty"`
	Default              Default           `yaml:"default,omitempty"`
	Choices              []Choice          `yaml:"choices,omitempty"`
	Spec                 []ArgSpec         `yaml:"spec,omitempty"`
	ResourceMethodParams map[string]string `yaml:"resource_method_params,omitempty"`
}

// ArgSpec describes an entry in an argument's spec list.
type ArgSpec struct {
	APIField string `yaml:"api_field,omitempty"`
}

// Choice describes one of the allowed values for a choice-typed argument.
type Choice struct {
	ArgValue  string `yaml:"arg_value,omitempty"`
	EnumValue string `yaml:"enum_value,omitempty"`
	HelpText  string `yaml:"help_text,omitempty"`
}

// ResourceSpec describes the resource referenced by an argument.
type ResourceSpec struct {
	Name                  string      `yaml:"name,omitempty"`
	PluralName            string      `yaml:"plural_name,omitempty"`
	Collection            string      `yaml:"collection,omitempty"`
	Attributes            []Attribute `yaml:"attributes,omitempty"`
	DisableAutoCompleters bool        `yaml:"disable_auto_completers"`
}

// Attribute describes a single attribute of a resource spec.
type Attribute struct {
	ParameterName string `yaml:"parameter_name,omitempty"`
	AttributeName string `yaml:"attribute_name,omitempty"`
	Help          string `yaml:"help,omitempty"`
	Property      string `yaml:"property,omitempty"`
}

// Request describes the API request issued by a command.
type Request struct {
	APIVersion   string            `yaml:"api_version,omitempty"`
	Collection   []string          `yaml:"collection,omitempty"`
	Method       string            `yaml:"method,omitempty"`
	StaticFields map[string]string `yaml:"static_fields,omitempty"`
}

// Async describes the long-running operation behavior of a command.
type Async struct {
	Collection            []string `yaml:"collection,omitempty"`
	ExtractResourceResult bool     `yaml:"extract_resource_result"`
}
