// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package declarative defines the schema for the gcloud declarative YAML
// command files emitted by the surfer.
//
// A handful of bool fields in this package intentionally omit the
// `omitempty` option on their yaml tag so that the key is always emitted,
// even when the value is the Go zero value (false). The gcloud declarative
// YAML schema requires those keys to always appear in the generated file.
// The fields that follow this rule are:
//
//   - Argument.IsPositional
//   - Argument.Required
//   - ResourceSpec.DisableAutoCompleters
//   - Update.ReadModifyUpdate
//   - Async.ExtractResourceResult
package declarative

//go:generate go run -tags configdocgen ../../../../cmd/config_doc_generate.go -input . -output ../../../../doc/gcloud/gcloud-declarative-schema.md -root Command -root-title Command -title "gcloud Declarative YAML"

// Command represents a single gcloud declarative YAML command definition.
type Command struct {
	// ReleaseTracks lists the gcloud release tracks (GA, BETA, ALPHA) that this command definition applies to.
	ReleaseTracks []string `yaml:"release_tracks,omitempty"`
	// AutoGenerated indicates that the YAML file was produced by a generator and should not be edited by hand.
	AutoGenerated bool `yaml:"auto_generated,omitempty"`
	// Hidden hides the command from help listings when true.
	Hidden bool `yaml:"hidden,omitempty"`
	// HelpText holds the command's help text.
	HelpText HelpText `yaml:"help_text"`
	// Arguments lists the command's positional and flag arguments.
	Arguments Arguments `yaml:"arguments"`
	// Request describes the API request issued by the command, if any.
	Request *Request `yaml:"request,omitempty"`
	// Async describes the long-running operation behavior of the command, if any.
	Async *Async `yaml:"async,omitempty"`
	// Response describes how to interpret the command's response, if any.
	Response *Response `yaml:"response,omitempty"`
	// Update describes how update commands handle field masks, if applicable.
	Update *Update `yaml:"update,omitempty"`
	// Output describes how the command's output should be formatted, if specified.
	Output *Output `yaml:"output,omitempty"`
}

// Update describes how update commands handle field masks.
type Update struct {
	// ReadModifyUpdate causes the command to read the resource, apply changes, then write it back when true.
	ReadModifyUpdate bool `yaml:"read_modify_update"`
	// DisableAutoFieldMask disables automatic generation of the update field mask when true.
	DisableAutoFieldMask bool `yaml:"disable_auto_field_mask,omitempty"`
}

// Output describes how command output should be formatted.
type Output struct {
	// Format specifies the gcloud output format string for the command.
	Format string `yaml:"format,omitempty"`
}

// Response describes how to interpret the response of a command.
type Response struct {
	// IDField names the field on the response that identifies the resource.
	IDField string `yaml:"id_field,omitempty"`
}

// HelpText describes the help text for a command.
type HelpText struct {
	// Brief is a single-line summary of the command.
	Brief string `yaml:"brief"`
	// Description is the long-form description of the command.
	Description string `yaml:"description"`
	// Examples provides example invocations of the command.
	Examples string `yaml:"examples,omitempty"`
}

// Default represents an optional default value for an argument.
type Default struct {
	// Value is the underlying default value emitted when present.
	Value *any
}

// IsZero reports whether d holds no value.
func (d Default) IsZero() bool {
	return d.Value == nil
}

// MarshalYAML implements yaml.Marshaler so that the underlying value is
// emitted directly when present.
func (d Default) MarshalYAML() (any, error) {
	if d.Value == nil {
		return nil, nil
	}
	return *d.Value, nil
}

// Arguments contains the argument definitions for a command.
type Arguments struct {
	// Params holds the list of argument definitions for the command.
	Params []Argument `yaml:"params,omitempty"`
}

// Argument describes a single command argument.
type Argument struct {
	// ArgName is the name of the argument as it appears on the command line.
	ArgName string `yaml:"arg_name,omitempty"`
	// APIField is the name of the request field this argument maps to.
	APIField string `yaml:"api_field,omitempty"`
	// HelpText is the help text shown for this argument.
	HelpText string `yaml:"help_text"`
	// Action specifies a special argument action, such as "store_true".
	Action string `yaml:"action,omitempty"`
	// IsPositional reports whether this argument is a positional argument.
	IsPositional bool `yaml:"is_positional"`
	// IsPrimaryResource reports whether this argument refers to the command's primary resource.
	IsPrimaryResource bool `yaml:"is_primary_resource,omitempty"`
	// RequestIDField names the request field used to carry this argument's identifier.
	RequestIDField string `yaml:"request_id_field,omitempty"`
	// ResourceSpec describes the resource referenced by this argument.
	ResourceSpec *ResourceSpec `yaml:"resource_spec,omitempty"`
	// Required reports whether the argument must be supplied by the user.
	Required bool `yaml:"required"`
	// Repeated reports whether the argument may be supplied multiple times.
	Repeated bool `yaml:"repeated,omitempty"`
	// Clearable reports whether the argument's value can be cleared.
	Clearable bool `yaml:"clearable,omitempty"`
	// Type specifies the argument's type when not a plain string.
	Type string `yaml:"type,omitempty"`
	// Default holds the argument's default value, if any.
	Default Default `yaml:"default,omitempty"`
	// Choices lists the allowed values for a choice-typed argument.
	Choices []Choice `yaml:"choices,omitempty"`
	// Spec lists nested argument specifications.
	Spec []ArgSpec `yaml:"spec,omitempty"`
	// ResourceMethodParams maps method parameter names to request field paths.
	ResourceMethodParams map[string]string `yaml:"resource_method_params,omitempty"`
}

// ArgSpec describes an entry in an argument's spec list.
type ArgSpec struct {
	// APIField is the name of the request field this spec entry maps to.
	APIField string `yaml:"api_field,omitempty"`
}

// Choice describes one of the allowed values for a choice-typed argument.
type Choice struct {
	// ArgValue is the value the user types on the command line.
	ArgValue string `yaml:"arg_value,omitempty"`
	// EnumValue is the corresponding API enum value.
	EnumValue string `yaml:"enum_value,omitempty"`
	// HelpText is the help text shown for this choice.
	HelpText string `yaml:"help_text,omitempty"`
}

// ResourceSpec describes the resource referenced by an argument.
type ResourceSpec struct {
	// Name is the singular resource name.
	Name string `yaml:"name,omitempty"`
	// PluralName is the plural resource name.
	PluralName string `yaml:"plural_name,omitempty"`
	// Collection is the resource's collection identifier.
	Collection string `yaml:"collection,omitempty"`
	// Attributes lists the attributes that identify the resource.
	Attributes []Attribute `yaml:"attributes,omitempty"`
	// DisableAutoCompleters turns off auto-completion for this resource when true.
	DisableAutoCompleters bool `yaml:"disable_auto_completers"`
}

// Attribute describes a single attribute of a resource spec.
type Attribute struct {
	// ParameterName is the name of the parameter in the API request.
	ParameterName string `yaml:"parameter_name,omitempty"`
	// AttributeName is the name of the attribute in the resource spec.
	AttributeName string `yaml:"attribute_name,omitempty"`
	// Help is the help text shown for this attribute.
	Help string `yaml:"help,omitempty"`
	// Property names the gcloud property that supplies a default value for this attribute.
	Property string `yaml:"property,omitempty"`
}

// Request describes the API request issued by a command.
type Request struct {
	// APIVersion is the API version used to issue the request.
	APIVersion string `yaml:"api_version,omitempty"`
	// Collection is the resource collection path used to issue the request.
	Collection []string `yaml:"collection,omitempty"`
	// Method is the API method invoked by the command.
	Method string `yaml:"method,omitempty"`
	// StaticFields sets request fields to fixed values.
	StaticFields map[string]string `yaml:"static_fields,omitempty"`
}

// Async describes the long-running operation behavior of a command.
type Async struct {
	// Collection is the resource collection path of the operation resource.
	Collection []string `yaml:"collection,omitempty"`
	// ExtractResourceResult extracts the target resource from the operation result when true.
	ExtractResourceResult bool `yaml:"extract_resource_result"`
}
