# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Filteredcommand filteredResource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class FilteredResourcesGa(base.Group):
  """Manage Filteredcommand filteredResource resources."""
