# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage API with long flag names resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class FieldflagnamesGa(base.Group):
  """Manage API with long flag names resources."""
