# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Resourcereference resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class ResourcereferenceGa(base.Group):
  """Manage Resourcereference resources."""
