# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Minimal output format method resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class MethodOutputFormatGa(base.Group):
  """Manage Minimal output format method resources."""
