# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Resourcestandard regionResource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class RegionResourcesGa(base.Group):
  """Manage Resourcestandard regionResource resources."""
