# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Custom Methods revision resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class RevisionsGa(base.Group):
  """Manage Custom Methods revision resources."""
