# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Methodcustom revision resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class RevisionsGa(base.Group):
  """Manage Methodcustom revision resources."""
