# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Updatemask resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class UpdatemaskGa(base.Group):
  """Manage Updatemask resources."""
