# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Methodoperations resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class MethodoperationsGa(base.Group):
  """Manage Methodoperations resources."""
