# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Multitype Resource deep resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class DeepsGa(base.Group):
  """Manage Multitype Resource deep resources."""
