# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Methodoutputformat resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class MethodoutputformatGa(base.Group):
  """Manage Methodoutputformat resources."""
