# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Regionalendpoints resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class RegionalendpointsGa(base.Group):
  """Manage Regionalendpoints resources."""
