# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Confirmationprompt resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class ConfirmationpromptGa(base.Group):
  """Manage Confirmationprompt resources."""
