# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Methodminimallist resource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class ResourcesGa(base.Group):
  """Manage Methodminimallist resource resources."""
