# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Hiddenfeature visible_resource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class VisibleResourcesGa(base.Group):
  """Manage Hiddenfeature visible_resource resources."""
