# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Resourcenonstandard resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class ResourcenonstandardGa(base.Group):
  """Manage Resourcenonstandard resources."""
