# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Hiddencommand resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class HiddencommandGa(base.Group):
  """Manage Hiddencommand resources."""
