# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Methodminimallist resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class MethodminimallistGa(base.Group):
  """Manage Methodminimallist resources."""
