# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Custom Methods resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class MethodCustomGa(base.Group):
  """Manage Custom Methods resources."""
