# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Standard Resource zone resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class ZonesGa(base.Group):
  """Manage Standard Resource zone resources."""
