# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Helptext resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class HelptextGa(base.Group):
  """Manage Helptext resources."""
