# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Fieldattributes resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class FieldattributesGa(base.Group):
  """Manage Fieldattributes resources."""
