# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Hiddenfeature hidden_resource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class HiddenResourcesGa(base.Group):
  """Manage Hiddenfeature hidden_resource resources."""
