# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Resourcenonstandard longResource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class LongResourcesGa(base.Group):
  """Manage Resourcenonstandard longResource resources."""
