# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Standard Resource zoneResource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class ZoneResourcesGa(base.Group):
  """Manage Standard Resource zoneResource resources."""
