name: Install protoc
runs:
  using: composite
  steps:
    - name: Install protoc
      run: |
        set -e
        curl -fsSL --retry 5 --retry-delay 15 -o /tmp/protoc.zip https://github.com/protocolbuffers/protobuf/releases/download/v$VERSION/protoc-$VERSION-linux-x86_64.zip
        sha512sum -c <(echo "$CHECKSUM /tmp/protoc.zip")
        cd /usr/local
        sudo unzip -o /tmp/protoc.zip
        protoc --version
      shell: bash
      env:
        VERSION: "31.0"
        CHECKSUM: 45776e351baa6c2a9ba3b05a20d5302c5226db0579a6279a540592244d9de9b5f80c9905e90b6a1cebda12c3f8a2bd15450b46d967ba2e80dfc26fb246a84654
