# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Fieldsimpletypes resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class FieldsimpletypesGa(base.Group):
  """Manage Fieldsimpletypes resources."""
