# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Minimal list method resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class MethodMinimalListGa(base.Group):
  """Manage Minimal list method resources."""
