# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Fieldcomplextypes resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class FieldcomplextypesGa(base.Group):
  """Manage Fieldcomplextypes resources."""
