# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Resourcestandard resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class ResourcestandardGa(base.Group):
  """Manage Resourcestandard resources."""
