# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Resourcestandard globalResource resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class GlobalResourcesGa(base.Group):
  """Manage Resourcestandard globalResource resources."""
