# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Resourcemultitype resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class ResourcemultitypeGa(base.Group):
  """Manage Resourcemultitype resources."""
