# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Hiddenfeature resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class HiddenfeatureGa(base.Group):
  """Manage Hiddenfeature resources."""
