# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Fieldoneof resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class FieldoneofGa(base.Group):
  """Manage Fieldoneof resources."""
