# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Async Methods resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class MethodasyncGa(base.Group):
  """Manage Async Methods resources."""
