# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Filteredcommand resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class FilteredcommandGa(base.Group):
  """Manage Filteredcommand resources."""
