# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Standard Resource parents resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class ParentsGa(base.Group):
  """Manage Standard Resource parents resources."""
