// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package language

import (
	"os"
	"path/filepath"
	"strings"

	"github.com/cbroglie/mustache"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

type mustacheProvider struct {
	impl    func(string) (string, error)
	dirname string
}

// Get gets the template contents.
func (p *mustacheProvider) Get(name string) (string, error) {
	if strings.HasPrefix(name, "/") {
		return p.impl(strings.TrimPrefix(name, "/") + ".mustache")
	}
	return p.impl(filepath.Join(p.dirname, name) + ".mustache")
}

// GenerateFromModel generates a number of files always using the api.API model
// as the input to the mustache template.
//
// This works well for languages like Go and Rust, where a single file can
// contain all the clients or messages generated by an API. We anticipate that
// other functions will be needed for languages like Java or C++, where it is
// conventional to have a single class per file.
func GenerateFromModel(outDir string, model *api.API, provider TemplateProvider, generatedFiles []GeneratedFile) error {
	for _, gen := range generatedFiles {
		if err := generateElement(outDir, model, provider, gen); err != nil {
			return err
		}
	}
	return nil
}

// GenerateService generates a single file using the api.Service model.
func GenerateService(outDir string, service *api.Service, provider TemplateProvider, gen GeneratedFile) error {
	return generateElement(outDir, service, provider, gen)
}

// GenerateMessage generates a single file using the api.Message model.
func GenerateMessage(outDir string, message *api.Message, provider TemplateProvider, gen GeneratedFile) error {
	return generateElement(outDir, message, provider, gen)
}

// GenerateEnum generates a single file using the api.Enum model.
func GenerateEnum(outDir string, enum *api.Enum, provider TemplateProvider, gen GeneratedFile) error {
	return generateElement(outDir, enum, provider, gen)
}

func generateElement(outDir string, element any, provider TemplateProvider, gen GeneratedFile) error {
	templateContents, err := provider(gen.TemplatePath)
	if err != nil {
		return err
	}
	destination := filepath.Join(outDir, gen.OutputPath)
	if err := os.MkdirAll(filepath.Dir(destination), 0755); err != nil {
		return err
	}
	nestedProvider := mustacheProvider{
		impl:    provider,
		dirname: filepath.Dir(gen.TemplatePath),
	}
	s, err := mustache.RenderPartials(templateContents, &nestedProvider, element)
	if err != nil {
		return err
	}
	return os.WriteFile(destination, []byte(s), 0666)
}
