# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Operation Methods operations resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class OperationsGa(base.Group):
  """Manage Operation Methods operations resources."""
