# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Methodcustom resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class MethodcustomGa(base.Group):
  """Manage Methodcustom resources."""
