// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"fmt"
	"slices"
	"strings"

	"github.com/googleapis/librarian/internal/sidekick/api"
	"github.com/iancoleman/strcase"
)

// commandBuilder holds the shared state needed to build a gcloud command
// definition from an API method. It eliminates repeated parameter passing
// across the build functions.
type commandBuilder struct {
	method  *api.Method
	config  *Config
	model   *api.API
	service *api.Service
}

// NewCommand constructs a single gcloud command definition from an API method.
func NewCommand(method *api.Method, config *Config, model *api.API, service *api.Service) (*Command, error) {
	b := &commandBuilder{
		method:  method,
		config:  config,
		model:   model,
		service: service,
	}
	return b.build()
}

// build assembles the complete command definition.
func (b *commandBuilder) build() (*Command, error) {
	rule := b.findHelpTextRule()

	cmd := &Command{
		AutoGenerated: true,
	}

	if len(b.config.APIs) > 0 {
		cmd.Hidden = b.config.APIs[0].RootIsHidden
	} else {
		cmd.Hidden = true
	}

	if rule != nil {
		cmd.HelpText = HelpText{
			Brief:       rule.HelpText.Brief,
			Description: rule.HelpText.Description,
			Examples:    strings.Join(rule.HelpText.Examples, "\n\n"),
		}
	}

	// Infer default release track from proto package.
	// TODO(https://github.com/googleapis/librarian/issues/3289): Allow gcloud config to overwrite the track for this command.
	inferredTrack := inferTrackFromPackage(b.method.Service.Package)
	cmd.ReleaseTracks = []string{strings.ToUpper(inferredTrack)}

	args, err := b.buildArguments()
	if err != nil {
		return nil, err
	}
	cmd.Arguments = args
	cmd.Request = b.buildRequest()

	if isList(b.method) {
		cmd.Response = &Response{
			IDField: "name",
		}
		cmd.Output = b.buildOutputConfig()
	}

	if isUpdate(b.method) {
		cmd.Update = &UpdateConfig{
			ReadModifyUpdate: true,
		}
	}

	if b.method.OperationInfo != nil {
		cmd.Async = b.buildAsync()
	}

	return cmd, nil
}

// buildArguments generates the set of arguments for a command by dispatching
// over each field in the method's request message.
func (b *commandBuilder) buildArguments() (Arguments, error) {
	if b.method.InputType == nil {
		return Arguments{}, nil
	}

	var params []Param
	for _, field := range b.method.InputType.Fields {
		// TODO(https://github.com/googleapis/librarian/issues/3413): Improve error handling strategy (Error vs Skip) and messaging.
		p, err := b.flattenField(field, field.JSONName)
		if err != nil {
			return Arguments{}, err
		}
		params = append(params, p...)
	}
	return Arguments{Params: params}, nil
}

// flattenField dispatches a single field to the appropriate handler.
// For nested messages, it recurses into the sub-fields.
//
// TODO(https://github.com/googleapis/librarian/issues/3412): Support arg groups for nested messages.
func (b *commandBuilder) flattenField(field *api.Field, prefix string) ([]Param, error) {
	switch {
	case b.shouldSkip(field):
		return nil, nil
	case isPrimaryResource(field, b.method):
		return []Param{b.primaryResourceParam(field)}, nil
	case field.MessageType != nil && !field.Map:
		// TODO(https://github.com/googleapis/librarian/issues/3287): Support arg groups.
		// TODO(https://github.com/googleapis/librarian/issues/3288): Handle arg name collisions with path prefixes.
		var params []Param
		for _, f := range field.MessageType.Fields {
			p, err := b.flattenField(f, fmt.Sprintf("%s.%s", prefix, f.JSONName))
			if err != nil {
				return nil, err
			}
			params = append(params, p...)
		}
		return params, nil
	default:
		p, err := b.newParam(field, prefix)
		if err != nil {
			return nil, err
		}
		return []Param{p}, nil
	}
}

// shouldSkip determines if a field should be excluded from the generated command arguments.
func (b *commandBuilder) shouldSkip(field *api.Field) bool {
	if isPrimaryResource(field, b.method) {
		return false
	}

	if field.Name == "parent" {
		return true
	}

	if field.Name == "name" {
		return true
	}

	if field.Name == "update_mask" {
		return true
	}

	if isList(b.method) {
		switch field.Name {
		case "page_size", "page_token", "filter", "order_by":
			return true
		}
	}

	if slices.Contains(field.Behavior, api.FIELD_BEHAVIOR_OUTPUT_ONLY) {
		return true
	}

	if isUpdate(b.method) && slices.Contains(field.Behavior, api.FIELD_BEHAVIOR_IMMUTABLE) {
		return true
	}

	return false
}

// newParam creates a single command-line argument from a proto field.
func (b *commandBuilder) newParam(field *api.Field, apiField string) (Param, error) {
	// TODO(https://github.com/googleapis/librarian/issues/3414): Abstract away casing logic in the model.
	param := Param{
		ArgName:  strcase.ToKebab(field.Name),
		APIField: apiField,
		Required: field.DocumentAsRequired(),
		Repeated: field.Repeated,
	}

	switch {
	case field.ResourceReference != nil:
		spec, err := b.resourceReferenceSpec(field)
		if err != nil {
			return Param{}, err
		}
		param.ResourceSpec = spec
		param.ResourceMethodParams = map[string]string{
			apiField: "{__relative_name__}",
		}
	case field.Map:
		param.Repeated = true
		param.Spec = []ArgSpec{
			{APIField: "key"},
			{APIField: "value"},
		}
	case field.EnumType != nil:
		for _, v := range field.EnumType.Values {
			if strings.HasSuffix(v.Name, "_UNSPECIFIED") {
				continue
			}
			param.Choices = append(param.Choices, Choice{
				ArgValue:  strcase.ToKebab(v.Name),
				EnumValue: v.Name,
			})
		}
	default:
		param.Type = getGcloudType(field.Typez)
	}

	if isUpdate(b.method) && param.Repeated {
		param.Clearable = true
	}

	if rule := b.findFieldHelpTextRule(field); rule != nil {
		param.HelpText = rule.HelpText.Brief
	} else {
		// TODO(https://github.com/googleapis/librarian/issues/3033): improve default help text inference
		param.HelpText = fmt.Sprintf("Value for the `%s` field.", strcase.ToKebab(field.Name))
	}
	return param, nil
}

// primaryResourceParam creates the main positional resource argument for a command.
func (b *commandBuilder) primaryResourceParam(field *api.Field) Param {
	resource := getResourceForMethod(b.method, b.model)
	var segments []api.PathSegment
	// TODO(https://github.com/googleapis/librarian/issues/3415): Support multiple resource patterns and multitype resources.
	if resource != nil && len(resource.Patterns) > 0 {
		segments = resource.Patterns[0]
	}

	if isList(b.method) {
		segments = getParentFromSegments(segments)
	}

	resourceName := strcase.ToSnake(strings.TrimSuffix(field.Name, "_id"))
	if field.Name == "name" || isList(b.method) {
		resourceName = getSingularFromSegments(segments)
	}

	var helpText string
	switch {
	case isCreate(b.method):
		helpText = fmt.Sprintf("The %s to create.", resourceName)
	case isList(b.method):
		helpText = fmt.Sprintf("The project and location for which to retrieve %s information.", getPluralFromSegments(segments))
	default:
		helpText = fmt.Sprintf("The %s to operate on.", resourceName)
	}

	collectionPath := getCollectionPathFromSegments(segments)
	shortServiceName := b.shortServiceName()

	param := Param{
		HelpText:          helpText,
		IsPositional:      !isList(b.method),
		IsPrimaryResource: true,
		Required:          true,
		ResourceSpec: &ResourceSpec{
			Name:                  resourceName,
			PluralName:            getPluralFromSegments(segments),
			Collection:            fmt.Sprintf("%s.%s", shortServiceName, collectionPath),
			DisableAutoCompleters: false,
			Attributes:            newAttributesFromSegments(segments),
		},
	}

	if isCreate(b.method) {
		param.RequestIDField = strcase.ToLowerCamel(field.Name)
	}

	return param
}

// resourceReferenceSpec creates a ResourceSpec for a field that references
// another resource type (e.g., a `--network` flag).
func (b *commandBuilder) resourceReferenceSpec(field *api.Field) (*ResourceSpec, error) {
	for _, def := range b.model.ResourceDefinitions {
		if def.Type == field.ResourceReference.Type {
			if len(def.Patterns) == 0 {
				return nil, fmt.Errorf("resource definition for %q has no patterns", def.Type)
			}
			// TODO(https://github.com/googleapis/librarian/issues/3415): Support multiple resource patterns and multitype resources.
			segments := def.Patterns[0]

			pluralName := def.Plural
			if pluralName == "" {
				pluralName = getPluralFromSegments(segments)
			}

			name := getSingularFromSegments(segments)
			shortServiceName := b.shortServiceName()
			baseCollectionPath := getCollectionPathFromSegments(segments)
			fullCollectionPath := fmt.Sprintf("%s.%s", shortServiceName, baseCollectionPath)

			return &ResourceSpec{
				Name:       name,
				PluralName: pluralName,
				Collection: fullCollectionPath,
				// TODO(https://github.com/googleapis/librarian/issues/3416): Investigate and enable auto-completers for referenced resources.
				DisableAutoCompleters: true,
				Attributes:            newAttributesFromSegments(segments),
			}, nil
		}
	}
	return nil, fmt.Errorf("resource definition not found for type %q", field.ResourceReference.Type)
}

// newAttributesFromSegments parses a structured resource pattern and extracts the attributes
// that make up the resource's name.
func newAttributesFromSegments(segments []api.PathSegment) []Attribute {
	var attributes []Attribute

	for i, part := range segments {
		if part.Variable == nil {
			continue
		}

		if len(part.Variable.FieldPath) == 0 {
			continue
		}
		name := part.Variable.FieldPath[len(part.Variable.FieldPath)-1]
		var parameterName string

		if i > 0 && segments[i-1].Literal != nil {
			parameterName = *segments[i-1].Literal + "Id"
		} else {
			parameterName = name + "sId"
		}

		attr := Attribute{
			AttributeName: name,
			ParameterName: parameterName,
			Help:          fmt.Sprintf("The %s id of the {resource} resource.", name),
		}

		if name == "project" {
			attr.Property = "core/project"
		}
		attributes = append(attributes, attr)
	}
	return attributes
}

// buildRequest creates the Request part of the command definition.
func (b *commandBuilder) buildRequest() *Request {
	req := &Request{
		APIVersion: b.apiVersion(),
		Collection: b.collectionPath(false),
	}

	// For custom methods (AIP-136), the method field must match the custom verb.
	if len(b.method.PathInfo.Bindings) > 0 && b.method.PathInfo.Bindings[0].PathTemplate.Verb != nil {
		req.Method = *b.method.PathInfo.Bindings[0].PathTemplate.Verb
	} else if !isStandardMethod(b.method) {
		commandName, _ := getCommandName(b.method)
		req.Method = strcase.ToLowerCamel(commandName)
	}

	return req
}

// buildAsync creates the Async part of the command definition for long-running operations.
func (b *commandBuilder) buildAsync() *Async {
	async := &Async{
		Collection: b.collectionPath(true),
	}

	resource := getResourceForMethod(b.method, b.model)
	if resource == nil {
		return async
	}

	responseTypeID := b.method.OperationInfo.ResponseTypeID
	responseTypeName := responseTypeID
	if idx := strings.LastIndex(responseTypeID, "."); idx != -1 {
		responseTypeName = responseTypeID[idx+1:]
	}

	singular := getSingularResourceNameForMethod(b.method, b.model)
	if strings.EqualFold(responseTypeName, singular) || strings.HasSuffix(resource.Type, "/"+responseTypeName) {
		async.ExtractResourceResult = true
	} else {
		async.ExtractResourceResult = false
	}

	return async
}

// collectionPath constructs the gcloud collection path(s) for a request or async operation.
func (b *commandBuilder) collectionPath(isAsync bool) []string {
	var collections []string
	shortServiceName := b.shortServiceName()

	for _, binding := range b.method.PathInfo.Bindings {
		if binding.PathTemplate == nil {
			continue
		}

		basePath := extractPathFromSegments(binding.PathTemplate.Segments)

		if basePath == "" {
			continue
		}

		if isAsync {
			if idx := strings.LastIndex(basePath, "."); idx != -1 {
				basePath = basePath[:idx] + ".operations"
			} else {
				basePath = "operations"
			}
		}

		fullPath := fmt.Sprintf("%s.%s", shortServiceName, basePath)
		collections = append(collections, fullPath)
	}

	slices.Sort(collections)
	return slices.Compact(collections)
}

// buildOutputConfig generates the output configuration for List commands.
func (b *commandBuilder) buildOutputConfig() *OutputConfig {
	if !isList(b.method) {
		return nil
	}

	resourceMsg := findResourceMessage(b.method.OutputType)
	if resourceMsg == nil {
		return nil
	}

	format := newFormat(resourceMsg)
	if format == "" {
		return nil
	}

	return &OutputConfig{
		Format: format,
	}
}

// newFormat generates a gcloud table format string from a message definition.
func newFormat(message *api.Message) string {
	var sb strings.Builder
	first := true

	for _, f := range message.Fields {
		if !isSafeName(f.JSONName) {
			continue
		}

		isScalar := f.Typez == api.STRING_TYPE ||
			f.Typez == api.INT32_TYPE || f.Typez == api.INT64_TYPE ||
			f.Typez == api.BOOL_TYPE || f.Typez == api.ENUM_TYPE ||
			f.Typez == api.DOUBLE_TYPE || f.Typez == api.FLOAT_TYPE

		if isScalar {
			if !first {
				sb.WriteString(",\n")
			}
			if f.Repeated {
				sb.WriteString(f.JSONName)
				sb.WriteString(".join(',')")
			} else {
				sb.WriteString(f.JSONName)
			}
			first = false
			continue
		}

		if f.MessageType != nil && strings.HasSuffix(f.TypezID, ".Timestamp") {
			if !first {
				sb.WriteString(",\n")
			}
			sb.WriteString(f.JSONName)
			first = false
		}
	}

	if sb.Len() == 0 {
		return ""
	}
	return fmt.Sprintf("table(\n%s)", sb.String())
}

// findHelpTextRule finds the help text rule from the config that applies to the current method.
func (b *commandBuilder) findHelpTextRule() *HelpTextRule {
	if b.config.APIs == nil {
		return nil
	}
	for _, api := range b.config.APIs {
		if api.HelpText == nil {
			continue
		}
		for _, rule := range api.HelpText.MethodRules {
			if rule.Selector == strings.TrimPrefix(b.method.ID, ".") {
				return rule
			}
		}
	}
	return nil
}

// findFieldHelpTextRule finds the help text rule from the config that applies to a field.
func (b *commandBuilder) findFieldHelpTextRule(field *api.Field) *HelpTextRule {
	if b.config.APIs == nil {
		return nil
	}
	for _, api := range b.config.APIs {
		if api.HelpText == nil {
			continue
		}
		for _, rule := range api.HelpText.FieldRules {
			if rule.Selector == field.ID {
				return rule
			}
		}
	}
	return nil
}

// apiVersion extracts the API version from the configuration.
func (b *commandBuilder) apiVersion() string {
	if len(b.config.APIs) > 0 {
		return b.config.APIs[0].APIVersion
	}
	return ""
}

// shortServiceName extracts the short service name from the default host
// (e.g., "parallelstore.googleapis.com" -> "parallelstore").
func (b *commandBuilder) shortServiceName() string {
	hostParts := strings.Split(b.service.DefaultHost, ".")
	return hostParts[0]
}
