// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
)

func TestRenderCommandGroup(t *testing.T) {
	data := commandGroupView{
		Name:       "instances",
		ModulePath: "googlecloudsdk.surface.instances",
		HelpText:   "Manage Compute Engine Instance resources.",
		Year:       2025,
		GA:         &trackView{Name: "GA", HelpText: "Manage Compute Engine Instance resources."},
		BETA:       &trackView{Name: "BETA", HelpText: "Manage Compute Engine Instance resources."},
	}

	var buf bytes.Buffer
	err := commandGroupTemplate.Execute(&buf, data)
	if err != nil {
		t.Fatalf("commandGroupTemplate.Execute() unexpected error: %v", err)
	}
	got := buf.String()

	want := `# -*- coding: utf-8 -*- #
# Copyright 2025 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Compute Engine Instance resources."""

from googlecloudsdk.calliope import base
from googlecloudsdk.surface.instances import _init_extensions as extensions


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
class InstancesGa(extensions.InstancesGa):
  """Manage Compute Engine Instance resources."""


@base.ReleaseTracks(base.ReleaseTrack.BETA)
@base.Autogenerated
class InstancesBeta(extensions.InstancesBeta):
  """Manage Compute Engine Instance resources."""

`
	if diff := cmp.Diff(want, got); diff != "" {
		t.Logf("Got:\n%s", got)
		t.Errorf("renderCommandGroup() mismatch (-want +got):\n%s", diff)
	}
}

func TestRenderInitExtensions(t *testing.T) {
	data := commandGroupView{
		Name:       "instances",
		ModulePath: "googlecloudsdk.surface.instances",
		HelpText:   "Manage Compute Engine Instance resources.",
		Year:       2025,
		IsRoot:     false,
	}

	var buf bytes.Buffer
	err := initExtensionsTemplate.Execute(&buf, data)
	if err != nil {
		t.Fatalf("initExtensionsTemplate.Execute() unexpected error: %v", err)
	}
	got := buf.String()

	want := `# -*- coding: utf-8 -*- #
# Copyright 2025 Google LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""File to add optional custom code to extend __init__.py."""
from googlecloudsdk.calliope import base


class InstancesAlpha(base.Group):
  """Optional no-auto-generated code for ALPHA."""


class InstancesBeta(base.Group):
  """Optional no-auto-generated code for BETA."""


class InstancesGa(base.Group):
  """Optional no-auto-generated code for GA."""
`
	if diff := cmp.Diff(want, got); diff != "" {
		t.Logf("Got:\n%s", got)
		t.Errorf("initExtensionsTemplate.Execute() mismatch (-want +got):\n%s", diff)
	}
}

func TestWriteCommandGroupFile(t *testing.T) {
	tmpDir := t.TempDir()
	ga := &CommandGroup{Name: "instances", HelpText: "Manage instances"}
	if err := writeCommandGroupFile(tmpDir, "googlecloudsdk.instances", "instances", groupTracks{ga: ga}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expectedPath := filepath.Join(tmpDir, "__init__.py")
	if _, err := os.Stat(expectedPath); os.IsNotExist(err) {
		t.Errorf("expected file %q to be generated", expectedPath)
	}
}

func TestWriteCommandGroupFile_Error(t *testing.T) {
	ga := &CommandGroup{Name: "instances", HelpText: "Manage instances"}
	err := writeCommandGroupFile("/dev/null/invalid/path", "googlecloudsdk.instances", "instances", groupTracks{ga: ga})
	if err == nil {
		t.Error("expected error writing to invalid path, got nil")
	}
}

func TestWriteCommandGroupTree(t *testing.T) {
	tmpDir := t.TempDir()

	tree := &CommandGroupsByTrack{
		GA: &CommandGroup{
			Name:     "users",
			HelpText: "Manage users.",
			Commands: map[string]*Command{
				"create": {},
			},
			Groups: map[string]*CommandGroup{
				"billing": {
					Name:     "billing",
					HelpText: "Manage user billing.",
					Commands: map[string]*Command{
						"cancel": {},
					},
				},
			},
		},
	}

	if err := writeCommandGroupTree(tmpDir, "googlecloudsdk", tree); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(tmpDir, "users", "__init__.py"),
		filepath.Join(tmpDir, "users", "billing", "__init__.py"),
		filepath.Join(tmpDir, "users", "billing", "cancel.yaml"),
		filepath.Join(tmpDir, "users", "billing", "_partials", "_cancel_ga.yaml"),
	}

	for _, f := range expectedFiles {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %q to be generated", f)
		}
	}
}

func TestGroupName(t *testing.T) {
	tests := []struct {
		name  string
		ga    *CommandGroup
		beta  *CommandGroup
		alpha *CommandGroup
		want  string
	}{
		{
			name: "only GA",
			ga:   &CommandGroup{Name: "instances"},
			want: "instances",
		},
		{
			name: "only Beta",
			beta: &CommandGroup{Name: "instances"},
			want: "instances",
		},
		{
			name:  "only Alpha",
			alpha: &CommandGroup{Name: "instances"},
			want:  "instances",
		},
		{
			name: "none",
			want: "",
		},
		{
			name: "precedence",
			ga:   &CommandGroup{Name: "ga-name"},
			beta: &CommandGroup{Name: "beta-name"},
			want: "ga-name",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := groupName(groupTracks{ga: tt.ga, beta: tt.beta, alpha: tt.alpha}); got != tt.want {
				t.Errorf("groupName() = %v, want %v", got, tt.want)
			}
		})
	}
}

func TestWriteCommandGroupFile_TrackCombinations(t *testing.T) {
	tmpDir := t.TempDir()

	tests := []struct {
		name           string
		ga             *CommandGroup
		beta           *CommandGroup
		alpha          *CommandGroup
		containsTracks []string
		omitsTracks    []string
	}{
		{
			name:           "GA and Beta",
			ga:             &CommandGroup{Name: "instances", HelpText: "G"},
			beta:           &CommandGroup{Name: "instances", HelpText: "B"},
			containsTracks: []string{"ReleaseTrack.GA", "ReleaseTrack.BETA"},
			omitsTracks:    []string{"ReleaseTrack.ALPHA"},
		},
		{
			name:           "Beta and Alpha",
			beta:           &CommandGroup{Name: "instances", HelpText: "B"},
			alpha:          &CommandGroup{Name: "instances", HelpText: "A"},
			containsTracks: []string{"ReleaseTrack.BETA", "ReleaseTrack.ALPHA"},
			omitsTracks:    []string{"ReleaseTrack.GA"},
		},
		{
			name:           "Only Alpha",
			alpha:          &CommandGroup{Name: "instances", HelpText: "A"},
			containsTracks: []string{"ReleaseTrack.ALPHA"},
			omitsTracks:    []string{"ReleaseTrack.GA", "ReleaseTrack.BETA"},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if err := writeCommandGroupFile(tmpDir, "googlecloudsdk.instances", "instances", groupTracks{ga: tt.ga, beta: tt.beta, alpha: tt.alpha}); err != nil {
				t.Fatalf("unexpected error: %v", err)
			}

			path := filepath.Join(tmpDir, "__init__.py")
			data, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("failed to read generated file: %v", err)
			}

			content := string(data)
			for _, track := range tt.containsTracks {
				if !strings.Contains(content, track) {
					t.Errorf("expected content to contain %q", track)
				}
			}
			for _, track := range tt.omitsTracks {
				if strings.Contains(content, track) {
					t.Errorf("expected content to NOT contain %q", track)
				}
			}
		})
	}
}

func TestWriteGroup_DirError(t *testing.T) {
	// Trying to create a directory where a file already exists should fail
	tmpDir := t.TempDir()
	filePath := filepath.Join(tmpDir, "instances")
	if err := os.WriteFile(filePath, []byte("test"), 0644); err != nil {
		t.Fatalf("failed to create test file: %v", err)
	}

	ga := &CommandGroup{Name: "instances"}
	err := writeGroup(tmpDir, "googlecloudsdk", groupTracks{ga: ga})
	if err == nil {
		t.Error("expected error when creating directory over an existing file, got nil")
	}
}

func TestWriteGroup_NoName(t *testing.T) {
	tmpDir := t.TempDir()
	err := writeGroup(tmpDir, "googlecloudsdk", groupTracks{})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// Should not generate any files or directories
	entries, err := os.ReadDir(tmpDir)
	if err != nil {
		t.Fatalf("failed to read dir: %v", err)
	}
	if len(entries) != 0 {
		t.Errorf("expected empty directory, got %d entries", len(entries))
	}
}
