// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
)

func writeCommandGroupTree(outputDir string, tree *CommandGroupsByTrack) error {
	return writeGroup(outputDir, tree.GA, tree.BETA, tree.ALPHA)
}

func writeGroup(outputDir string, ga, beta, alpha *CommandGroup) error {
	name := groupName(ga, beta, alpha)
	if name == "" {
		return nil
	}

	groupDir := filepath.Join(outputDir, strcase.ToSnake(name))
	if err := os.MkdirAll(groupDir, 0755); err != nil {
		return err
	}

	if err := writeCommandGroupFile(groupDir, name, ga, beta, alpha); err != nil {
		return err
	}

	if err := writeGroupCommands(groupDir, ga, beta, alpha); err != nil {
		return err
	}

	return writeGroupSubgroups(groupDir, ga, beta, alpha)
}

func groupName(ga, beta, alpha *CommandGroup) string {
	if ga != nil {
		return ga.Name
	}
	if beta != nil {
		return beta.Name
	}
	if alpha != nil {
		return alpha.Name
	}
	return ""
}

func writeGroupCommands(groupDir string, ga, beta, alpha *CommandGroup) error {
	cmdNames := make(map[string]bool)
	tracks := []*CommandGroup{ga, beta, alpha}
	for _, g := range tracks {
		if g != nil {
			for n := range g.Commands {
				cmdNames[n] = true
			}
		}
	}

	for verb := range cmdNames {
		var gaCmd, betaCmd, alphaCmd *Command
		if ga != nil {
			gaCmd = ga.Commands[verb]
		}
		if beta != nil {
			betaCmd = beta.Commands[verb]
		}
		if alpha != nil {
			alphaCmd = alpha.Commands[verb]
		}

		if err := writeCommandFiles(groupDir, verb, gaCmd, betaCmd, alphaCmd); err != nil {
			return err
		}
	}
	return nil
}

func writeGroupSubgroups(groupDir string, ga, beta, alpha *CommandGroup) error {
	subNames := make(map[string]bool)
	tracks := []*CommandGroup{ga, beta, alpha}
	for _, g := range tracks {
		if g != nil {
			for n := range g.Groups {
				subNames[n] = true
			}
		}
	}

	for sub := range subNames {
		var gaSub, betaSub, alphaSub *CommandGroup
		if ga != nil {
			gaSub = ga.Groups[sub]
		}
		if beta != nil {
			betaSub = beta.Groups[sub]
		}
		if alpha != nil {
			alphaSub = alpha.Groups[sub]
		}

		if err := writeGroup(groupDir, gaSub, betaSub, alphaSub); err != nil {
			return err
		}
	}
	return nil
}

func writeCommandGroupFile(dir string, name string, ga, beta, alpha *CommandGroup) error {
	path := filepath.Join(dir, "__init__.py")

	var primaryHelpText string
	var gaView, betaView, alphaView *trackView

	if ga != nil {
		gaView = &trackView{Name: "GA", HelpText: ga.HelpText}
		if primaryHelpText == "" {
			primaryHelpText = ga.HelpText
		}
	}
	if beta != nil {
		betaView = &trackView{Name: "BETA", HelpText: beta.HelpText}
		if primaryHelpText == "" {
			primaryHelpText = beta.HelpText
		}
	}
	if alpha != nil {
		alphaView = &trackView{Name: "ALPHA", HelpText: alpha.HelpText}
		if primaryHelpText == "" {
			primaryHelpText = alpha.HelpText
		}
	}

	view := commandGroupView{
		Name:     name,
		HelpText: primaryHelpText,
		GA:       gaView,
		BETA:     betaView,
		ALPHA:    alphaView,
	}

	var buf bytes.Buffer
	if err := commandGroupTemplate.Execute(&buf, view); err != nil {
		return err
	}

	return os.WriteFile(path, []byte(strings.TrimSpace(buf.String())+"\n"), 0644)
}

type trackView struct {
	Name     string
	HelpText string
}

type commandGroupView struct {
	Name     string
	HelpText string
	GA       *trackView
	BETA     *trackView
	ALPHA    *trackView
}

var commandGroupTemplate = template.Must(template.New("__init__.py").Funcs(template.FuncMap{
	"toCamel": strcase.ToCamel,
}).Parse(`# NOTE: This file is autogenerated and should not be edited by hand.
"""{{.HelpText}}"""

from googlecloudsdk.calliope import base
{{if .GA}}

@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class {{$.Name | toCamel}}Ga(base.Group):
  """{{.GA.HelpText}}"""
{{end}}
{{if .BETA}}

@base.ReleaseTracks(base.ReleaseTrack.BETA)
@base.Autogenerated
@base.Hidden
class {{$.Name | toCamel}}Beta(base.Group):
  """{{.BETA.HelpText}}"""
{{end}}
{{if .ALPHA}}

@base.ReleaseTracks(base.ReleaseTrack.ALPHA)
@base.Autogenerated
@base.Hidden
class {{$.Name | toCamel}}Alpha(base.Group):
  """{{.ALPHA.HelpText}}"""
{{end}}`))
