// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/yaml"
)

// partialsHeader is the directive that tells gcloud to look in the `_partials` directory
// for command definitions. This allows for sharing definitions across release tracks.
const partialsHeader = "_PARTIALS_: true\n"

func writeCommandFiles(resourceDir string, verb string, ga, beta, alpha *Command) error {
	if ga == nil && beta == nil && alpha == nil {
		return nil
	}

	partialsDir := filepath.Join(resourceDir, "_partials")
	if err := os.MkdirAll(partialsDir, 0755); err != nil {
		return fmt.Errorf("failed to create partials directory: %w", err)
	}

	mainCmdPath := filepath.Join(resourceDir, fmt.Sprintf("%s.yaml", verb))
	if err := os.WriteFile(mainCmdPath, []byte(partialsHeader), 0644); err != nil {
		return fmt.Errorf("failed to write main command file for %q: %w", verb, err)
	}

	if err := writePartialFile(partialsDir, verb, "GA", ga); err != nil {
		return err
	}
	if err := writePartialFile(partialsDir, verb, "BETA", beta); err != nil {
		return err
	}
	if err := writePartialFile(partialsDir, verb, "ALPHA", alpha); err != nil {
		return err
	}

	return nil
}

func writePartialFile(partialsDir string, verb string, track string, cmd *Command) error {
	if cmd == nil {
		return nil
	}

	b, err := marshalCommand(cmd, track)
	if err != nil {
		return fmt.Errorf("failed to marshal partial command for %q in %s track: %w", verb, track, err)
	}

	trackName := strings.ToLower(track)
	partialFileName := fmt.Sprintf("_%s_%s.yaml", verb, trackName)
	partialCmdPath := filepath.Join(partialsDir, partialFileName)

	if err := os.WriteFile(partialCmdPath, b, 0644); err != nil {
		return fmt.Errorf("failed to write partial command file for %q: %w", verb, err)
	}
	return nil
}

// marshalCommand converts a Command into a YAML byte payload matching the schema.
func marshalCommand(cmd *Command, track string) ([]byte, error) {
	yamlCmd := mapCommandToYAML(cmd, track)
	cmdList := []*yamlCommand{yamlCmd}
	return yaml.Marshal(cmdList)
}

func mapCommandToYAML(c *Command, track string) *yamlCommand {
	y := &yamlCommand{
		ReleaseTracks: []string{track},
		AutoGenerated: true,
		Hidden:        c.Hidden,
		HelpText: yamlHelpText{
			Brief:       c.HelpText.Brief,
			Description: c.HelpText.Description,
			Examples:    c.HelpText.Examples,
		},
		Arguments: yamlArguments{
			Params: mapArgumentsToYAML(c.Arguments),
		},
	}
	if c.APIVersion != "" || len(c.Collection) > 0 || c.Method != "" {
		y.Request = &yamlRequest{
			APIVersion: c.APIVersion,
			Collection: c.Collection,
			Method:     c.Method,
		}
	}
	if c.Async != nil {
		y.Async = &yamlAsync{
			Collection:            c.Async.Collection,
			ExtractResourceResult: c.Async.ExtractResourceResult,
		}
	}
	if c.ResponseIDField != "" {
		y.Response = &yamlResponse{
			IDField: c.ResponseIDField,
		}
	}
	if c.ReadModifyUpdate || c.DisableAutoFieldMask {
		y.Update = &yamlUpdateConfig{
			ReadModifyUpdate:     c.ReadModifyUpdate,
			DisableAutoFieldMask: c.DisableAutoFieldMask,
		}
	}
	if c.OutputFormat != "" {
		y.Output = &yamlOutputConfig{
			Format: c.OutputFormat,
		}
	}
	return y
}

func mapArgumentsToYAML(args []Argument) []yamlArgument {
	var ya []yamlArgument
	for _, a := range args {
		ya = append(ya, yamlArgument{
			ArgName:              a.ArgName,
			APIField:             a.APIField,
			HelpText:             a.HelpText,
			IsPositional:         a.IsPositional,
			IsPrimaryResource:    a.IsPrimaryResource,
			RequestIDField:       a.RequestIDField,
			ResourceSpec:         mapResourceSpecToYAML(a.ResourceSpec),
			Required:             a.Required,
			Repeated:             a.Repeated,
			Clearable:            a.Clearable,
			Type:                 a.Type,
			Choices:              mapChoicesToYAML(a.Choices),
			Spec:                 mapArgSpecsToYAML(a.Spec),
			ResourceMethodParams: a.ResourceMethodParams,
		})
	}
	return ya
}

func mapResourceSpecToYAML(spec *ResourceSpec) *yamlResourceSpec {
	if spec == nil {
		return nil
	}
	var attrs []yamlAttribute
	for _, a := range spec.Attributes {
		attrs = append(attrs, yamlAttribute(a))
	}
	return &yamlResourceSpec{
		Name:                  spec.Name,
		PluralName:            spec.PluralName,
		Collection:            spec.Collection,
		Attributes:            attrs,
		DisableAutoCompleters: spec.DisableAutoCompleters,
	}
}

func mapArgSpecsToYAML(specs []ArgSpec) []yamlArgSpec {
	var yamlSpecs []yamlArgSpec
	for _, s := range specs {
		yamlSpecs = append(yamlSpecs, yamlArgSpec(s))
	}
	return yamlSpecs
}

func mapChoicesToYAML(choices []Choice) []yamlChoice {
	var yamlChoices []yamlChoice
	for _, c := range choices {
		yamlChoices = append(yamlChoices, yamlChoice(c))
	}
	return yamlChoices
}

type yamlCommand struct {
	ReleaseTracks []string          `yaml:"release_tracks,omitempty"`
	AutoGenerated bool              `yaml:"auto_generated,omitempty"`
	Hidden        bool              `yaml:"hidden,omitempty"`
	HelpText      yamlHelpText      `yaml:"help_text"`
	Arguments     yamlArguments     `yaml:"arguments"`
	Request       *yamlRequest      `yaml:"request,omitempty"`
	Async         *yamlAsync        `yaml:"async,omitempty"`
	Response      *yamlResponse     `yaml:"response,omitempty"`
	Update        *yamlUpdateConfig `yaml:"update,omitempty"`
	Output        *yamlOutputConfig `yaml:"output,omitempty"`
}

type yamlUpdateConfig struct {
	ReadModifyUpdate     bool `yaml:"read_modify_update"`
	DisableAutoFieldMask bool `yaml:"disable_auto_field_mask,omitempty"`
}

type yamlOutputConfig struct {
	Format string `yaml:"format,omitempty"`
}

type yamlResponse struct {
	IDField string `yaml:"id_field,omitempty"`
}

type yamlHelpText struct {
	Brief       string `yaml:"brief"`
	Description string `yaml:"description"`
	Examples    string `yaml:"examples,omitempty"`
}

type yamlArguments struct {
	Params []yamlArgument `yaml:"params,omitempty"`
}

type yamlArgument struct {
	ArgName              string            `yaml:"arg_name,omitempty"`
	APIField             string            `yaml:"api_field,omitempty"`
	HelpText             string            `yaml:"help_text"`
	IsPositional         bool              `yaml:"is_positional"`
	IsPrimaryResource    bool              `yaml:"is_primary_resource"`
	RequestIDField       string            `yaml:"request_id_field,omitempty"`
	ResourceSpec         *yamlResourceSpec `yaml:"resource_spec,omitempty"`
	Required             bool              `yaml:"required"`
	Repeated             bool              `yaml:"repeated"`
	Clearable            bool              `yaml:"clearable,omitempty"`
	Type                 string            `yaml:"type,omitempty"`
	Choices              []yamlChoice      `yaml:"choices,omitempty"`
	Spec                 []yamlArgSpec     `yaml:"spec,omitempty"`
	ResourceMethodParams map[string]string `yaml:"resource_method_params,omitempty"`
}

type yamlArgSpec struct {
	APIField string `yaml:"api_field,omitempty"`
}

type yamlChoice struct {
	ArgValue  string `yaml:"arg_value,omitempty"`
	EnumValue string `yaml:"enum_value,omitempty"`
	HelpText  string `yaml:"help_text,omitempty"`
}

type yamlResourceSpec struct {
	Name                  string          `yaml:"name,omitempty"`
	PluralName            string          `yaml:"plural_name,omitempty"`
	Collection            string          `yaml:"collection,omitempty"`
	Attributes            []yamlAttribute `yaml:"attributes,omitempty"`
	DisableAutoCompleters bool            `yaml:"disable_auto_completers"`
}

type yamlAttribute struct {
	ParameterName string `yaml:"parameter_name,omitempty"`
	AttributeName string `yaml:"attribute_name,omitempty"`
	Help          string `yaml:"help,omitempty"`
	Property      string `yaml:"property,omitempty"`
}

type yamlRequest struct {
	APIVersion string   `yaml:"api_version,omitempty"`
	Collection []string `yaml:"collection,omitempty"`
	Method     string   `yaml:"method,omitempty"`
}

type yamlAsync struct {
	Collection            []string `yaml:"collection,omitempty"`
	ExtractResourceResult bool     `yaml:"extract_resource_result"`
}
