// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/googleapis/librarian/internal/yaml"
	"github.com/iancoleman/strcase"
)

// partialsHeader is the directive that tells gcloud to look in the `_partials` directory
// for command definitions. This allows for sharing definitions across release tracks.
const partialsHeader = "_PARTIALS_: true\n"

// renderCommandGroup executes the command group template directly into an [io.Writer].
func renderCommandGroup(w io.Writer, data CommandGroup) error {
	return commandGroupTemplate.Execute(w, data)
}

// writeCommandGroupFile writes the Python __init__.py required for a gcloud command group.
func writeCommandGroupFile(dir string, data CommandGroup) error {
	path := filepath.Join(dir, "__init__.py")

	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	// We stream the template results directly into the file.
	// No intermediate []byte slice is created.
	return renderCommandGroup(f, data)
}

var commandGroupTemplate = template.Must(template.New("__init__.py").Funcs(template.FuncMap{
	"toCamel": strcase.ToCamel,
}).Parse(`# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage {{.ServiceTitle}}{{if .ResourceSingular}} {{.ResourceSingular}}{{end}} resources."""

from googlecloudsdk.calliope import base


{{range .Tracks}}@base.ReleaseTracks(base.ReleaseTrack.{{.}})
@base.Autogenerated
@base.Hidden
class {{$.ClassNamePrefix}}{{. | toCamel}}(base.Group):
  """Manage {{$.ServiceTitle}}{{if $.ResourceSingular}} {{$.ResourceSingular}}{{end}} resources."""


{{end}}`))

// marshalCommand converts a Command into a YAML byte payload matching the schema.
func marshalCommand(cmd *Command) ([]byte, error) {
	yamlCmd := mapCommandToYAML(cmd)
	cmdList := []*yamlCommand{yamlCmd}
	return yaml.Marshal(cmdList)
}

// writeCommandFiles handles outputting the main YAML stub and the release-track
// specific partial definitions for a generated Command.
func writeCommandFiles(resourceDir string, verb string, cmd *Command, methodName string) error {
	partialsDir := filepath.Join(resourceDir, "_partials")
	if err := os.MkdirAll(partialsDir, 0755); err != nil {
		return fmt.Errorf("failed to create partials directory: %w", err)
	}

	b, err := marshalCommand(cmd)
	if err != nil {
		return fmt.Errorf("failed to marshal partial command for %q: %w", methodName, err)
	}

	mainCmdPath := filepath.Join(resourceDir, fmt.Sprintf("%s.yaml", verb))
	if err := os.WriteFile(mainCmdPath, []byte(partialsHeader), 0644); err != nil {
		return fmt.Errorf("failed to write main command file for %q: %w", methodName, err)
	}

	// Generate a partial file for each release track.
	for _, track := range cmd.ReleaseTracks {
		trackName := strings.ToLower(track)
		partialFileName := fmt.Sprintf("_%s_%s.yaml", verb, trackName)
		partialCmdPath := filepath.Join(partialsDir, partialFileName)

		if err := os.WriteFile(partialCmdPath, b, 0644); err != nil {
			return fmt.Errorf("failed to write partial command file for %q: %w", methodName, err)
		}
	}
	return nil
}

func mapCommandToYAML(c *Command) *yamlCommand {
	y := &yamlCommand{
		ReleaseTracks: c.ReleaseTracks,
		AutoGenerated: true,
		Hidden:        c.Hidden,
		HelpText: yamlHelpText{
			Brief:       c.HelpText.Brief,
			Description: c.HelpText.Description,
			Examples:    c.HelpText.Examples,
		},
		Arguments: yamlArguments{
			Params: mapArgumentsToYAML(c.Arguments),
		},
	}
	if c.Request != nil {
		y.Request = &yamlRequest{
			APIVersion: c.Request.APIVersion,
			Collection: c.Request.Collection,
			Method:     c.Request.Method,
		}
	}
	if c.Async != nil {
		y.Async = &yamlAsync{
			Collection:            c.Async.Collection,
			ExtractResourceResult: c.Async.ExtractResourceResult,
		}
	}
	if c.ResponseIDField != "" {
		y.Response = &yamlResponse{IDField: c.ResponseIDField}
	}
	if c.ReadModifyUpdate || c.DisableAutoFieldMask {
		y.Update = &yamlUpdateConfig{
			ReadModifyUpdate:     c.ReadModifyUpdate,
			DisableAutoFieldMask: c.DisableAutoFieldMask,
		}
	}
	if c.OutputFormat != "" {
		y.Output = &yamlOutputConfig{Format: c.OutputFormat}
	}
	return y
}

func mapArgumentsToYAML(args []Argument) []yamlArgument {
	ya := make([]yamlArgument, len(args))
	for i, p := range args {
		ya[i] = yamlArgument{
			ArgName:              p.ArgName,
			APIField:             p.APIField,
			HelpText:             p.HelpText,
			IsPositional:         p.IsPositional,
			IsPrimaryResource:    p.IsPrimaryResource,
			RequestIDField:       p.RequestIDField,
			ResourceSpec:         mapResourceSpecToYAML(p.ResourceSpec),
			Required:             p.Required,
			Repeated:             p.Repeated,
			Clearable:            p.Clearable,
			Type:                 p.Type,
			Choices:              mapChoicesToYAML(p.Choices),
			Spec:                 mapArgSpecsToYAML(p.Spec),
			ResourceMethodParams: p.ResourceMethodParams,
		}
	}
	return ya
}

func mapResourceSpecToYAML(spec *ResourceSpec) *yamlResourceSpec {
	if spec == nil {
		return nil
	}
	var attrs []yamlAttribute
	for _, a := range spec.Attributes {
		attrs = append(attrs, yamlAttribute(a))
	}
	return &yamlResourceSpec{
		Name:                  spec.Name,
		PluralName:            spec.PluralName,
		Collection:            spec.Collection,
		Attributes:            attrs,
		DisableAutoCompleters: spec.DisableAutoCompleters,
	}
}

func mapArgSpecsToYAML(specs []ArgSpec) []yamlArgSpec {
	var yamlSpecs []yamlArgSpec
	for _, s := range specs {
		yamlSpecs = append(yamlSpecs, yamlArgSpec(s))
	}
	return yamlSpecs
}

func mapChoicesToYAML(choices []Choice) []yamlChoice {
	var yamlChoices []yamlChoice
	for _, c := range choices {
		yamlChoices = append(yamlChoices, yamlChoice(c))
	}
	return yamlChoices
}

type yamlCommand struct {
	ReleaseTracks []string          `yaml:"release_tracks,omitempty"`
	AutoGenerated bool              `yaml:"auto_generated,omitempty"`
	Hidden        bool              `yaml:"hidden,omitempty"`
	HelpText      yamlHelpText      `yaml:"help_text"`
	Arguments     yamlArguments     `yaml:"arguments"`
	Request       *yamlRequest      `yaml:"request,omitempty"`
	Async         *yamlAsync        `yaml:"async,omitempty"`
	Response      *yamlResponse     `yaml:"response,omitempty"`
	Update        *yamlUpdateConfig `yaml:"update,omitempty"`
	Output        *yamlOutputConfig `yaml:"output,omitempty"`
}

type yamlUpdateConfig struct {
	ReadModifyUpdate     bool `yaml:"read_modify_update"`
	DisableAutoFieldMask bool `yaml:"disable_auto_field_mask,omitempty"`
}

type yamlOutputConfig struct {
	Format string `yaml:"format,omitempty"`
}

type yamlResponse struct {
	IDField string `yaml:"id_field,omitempty"`
}

type yamlHelpText struct {
	Brief       string `yaml:"brief"`
	Description string `yaml:"description"`
	Examples    string `yaml:"examples,omitempty"`
}

type yamlArguments struct {
	Params []yamlArgument `yaml:"params,omitempty"`
}

type yamlArgument struct {
	ArgName              string            `yaml:"arg_name,omitempty"`
	APIField             string            `yaml:"api_field,omitempty"`
	HelpText             string            `yaml:"help_text"`
	IsPositional         bool              `yaml:"is_positional"`
	IsPrimaryResource    bool              `yaml:"is_primary_resource"`
	RequestIDField       string            `yaml:"request_id_field,omitempty"`
	ResourceSpec         *yamlResourceSpec `yaml:"resource_spec,omitempty"`
	Required             bool              `yaml:"required"`
	Repeated             bool              `yaml:"repeated"`
	Clearable            bool              `yaml:"clearable,omitempty"`
	Type                 string            `yaml:"type,omitempty"`
	Choices              []yamlChoice      `yaml:"choices,omitempty"`
	Spec                 []yamlArgSpec     `yaml:"spec,omitempty"`
	ResourceMethodParams map[string]string `yaml:"resource_method_params,omitempty"`
}

type yamlArgSpec struct {
	APIField string `yaml:"api_field,omitempty"`
}

type yamlChoice struct {
	ArgValue  string `yaml:"arg_value,omitempty"`
	EnumValue string `yaml:"enum_value,omitempty"`
	HelpText  string `yaml:"help_text,omitempty"`
}

type yamlResourceSpec struct {
	Name                  string          `yaml:"name,omitempty"`
	PluralName            string          `yaml:"plural_name,omitempty"`
	Collection            string          `yaml:"collection,omitempty"`
	Attributes            []yamlAttribute `yaml:"attributes,omitempty"`
	DisableAutoCompleters bool            `yaml:"disable_auto_completers"`
}

type yamlAttribute struct {
	ParameterName string `yaml:"parameter_name,omitempty"`
	AttributeName string `yaml:"attribute_name,omitempty"`
	Help          string `yaml:"help,omitempty"`
	Property      string `yaml:"property,omitempty"`
}

type yamlRequest struct {
	APIVersion string   `yaml:"api_version,omitempty"`
	Collection []string `yaml:"collection,omitempty"`
	Method     string   `yaml:"method,omitempty"`
}

type yamlAsync struct {
	Collection            []string `yaml:"collection,omitempty"`
	ExtractResourceResult bool     `yaml:"extract_resource_result"`
}
