// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package gcloud

import (
	"bytes"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/googleapis/librarian/internal/yaml"
)

func TestYAMLCommandSchema(t *testing.T) {
	const root = "testdata/parallelstore/surface"
	var files []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if filepath.Ext(path) != ".yaml" {
			return nil
		}
		files = append(files, path)
		return nil
	})
	if err != nil {
		t.Fatal(err)
	}

	for _, filename := range files {
		t.Run(filename, func(t *testing.T) {
			data, err := os.ReadFile(filename)
			if err != nil {
				t.Fatal(err)
			}
			data = bytes.ReplaceAll(data, []byte("\r\n"), []byte("\n"))

			if strings.Contains(string(data), "_PARTIALS_") {
				return
			}

			commands, err := yaml.Unmarshal[[]*yamlCommand](data)
			if err != nil {
				t.Fatal(err)
			}

			marshaled, err := yaml.Marshal(commands)
			if err != nil {
				t.Fatal(err)
			}

			roundTripped, err := yaml.Unmarshal[[]*yamlCommand](marshaled)
			if err != nil {
				t.Fatal(err)
			}

			if diff := cmp.Diff(commands, roundTripped); diff != "" {
				t.Errorf("mismatch (-want +got):\n%s", diff)
			}
		})
	}
}

func TestRenderCommandGroup(t *testing.T) {
	data := CommandGroup{
		ServiceTitle:     "Compute Engine",
		ResourceSingular: "Instance",
		ClassNamePrefix:  "Instances",
		Tracks:           []string{"BETA", "GA"},
	}

	var buf bytes.Buffer
	err := renderCommandGroup(&buf, data)
	if err != nil {
		t.Fatalf("renderCommandGroup() unexpected error: %v", err)
	}
	got := buf.String()

	want := `# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Compute Engine Instance resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.BETA)
@base.Autogenerated
@base.Hidden
class InstancesBeta(base.Group):
  """Manage Compute Engine Instance resources."""


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class InstancesGa(base.Group):
  """Manage Compute Engine Instance resources."""
`
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("renderCommandGroup() mismatch (-want +got):\n%s", diff)
	}
}

func TestMarshalCommand(t *testing.T) {
	cmd := &Command{
		ReleaseTracks: []string{"GA"},
		Arguments: []Argument{
			{
				ArgName: "test-arg",
				Type:    "string",
			},
		},
	}

	b, err := marshalCommand(cmd)
	if err != nil {
		t.Fatalf("marshalCommand() unexpected error: %v", err)
	}

	got := string(b)
	want := `- release_tracks:
    - GA
  auto_generated: true
  help_text:
    brief: ""
    description: ""
  arguments:
    params:
      - arg_name: test-arg
        help_text: ""
        is_positional: false
        is_primary_resource: false
        required: false
        repeated: false
        type: string
  request: {}
`
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("marshalCommand() mismatch (-want +got):\n%s", diff)
	}
}

func TestWriteCommandGroupFile(t *testing.T) {
	tmpDir := t.TempDir()
	if err := writeCommandGroupFile(tmpDir, CommandGroup{}); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expectedPath := filepath.Join(tmpDir, "__init__.py")
	if _, err := os.Stat(expectedPath); os.IsNotExist(err) {
		t.Errorf("expected file %q to be generated", expectedPath)
	}
}

func TestWriteCommandFiles(t *testing.T) {
	tmpDir := t.TempDir()
	cmd := &Command{
		ReleaseTracks: []string{"BETA", "GA"},
	}
	verb := "create"

	if err := writeCommandFiles(tmpDir, verb, cmd, "TestMethod"); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	expectedFiles := []string{
		filepath.Join(tmpDir, "create.yaml"),
		filepath.Join(tmpDir, "_partials", "_create_beta.yaml"),
		filepath.Join(tmpDir, "_partials", "_create_ga.yaml"),
	}

	for _, f := range expectedFiles {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected file %q to be generated", f)
		}
	}
}

func TestWriteCommandGroupFile_Error(t *testing.T) {
	err := writeCommandGroupFile("/dev/null/invalid/path", CommandGroup{})
	if err == nil {
		t.Error("expected error writing to invalid path, got nil")
	}
}

func TestWriteCommandFiles_Error(t *testing.T) {
	cmd := &Command{ReleaseTracks: []string{"GA"}}
	err := writeCommandFiles("/dev/null/invalid/path", "create", cmd, "Method")
	if err == nil {
		t.Error("expected error writing to invalid path, got nil")
	}
}

func TestMapCommandToYAML(t *testing.T) {
	cmd := &Command{
		ReleaseTracks: []string{"GA"},
		Hidden:        true,
		HelpText: HelpText{
			Brief:       "brief",
			Description: "desc",
			Examples:    "ex",
		},
		Collection: []string{"c"},
		APIVersion: "v1",
		Method:     "m",
		Async: &Async{
			Collection:            []string{"ac"},
			ExtractResourceResult: true,
		},
		ReadModifyUpdate: true,
		ResponseIDField:  "id",
		OutputFormat:     "table",
		Arguments: []Argument{
			{
				ArgName: "arg",
				Spec: []ArgSpec{
					{APIField: "s"},
				},
				Choices: []Choice{
					{ArgValue: "av", EnumValue: "ev", HelpText: "ch"},
				},
				ResourceSpec: &ResourceSpec{
					Name:       "n",
					PluralName: "pn",
					Collection: "c",
					Attributes: []Attribute{
						{AttributeName: "an"},
					},
					DisableAutoCompleters: true,
				},
			},
		},
	}

	got := mapCommandToYAML(cmd)

	want := &yamlCommand{
		ReleaseTracks: []string{"GA"},
		AutoGenerated: true,
		Hidden:        true,
		HelpText: yamlHelpText{
			Brief:       "brief",
			Description: "desc",
			Examples:    "ex",
		},
		Request: yamlRequest{
			Collection: []string{"c"},
			APIVersion: "v1",
			Method:     "m",
		},
		Async: &yamlAsync{
			Collection:            []string{"ac"},
			ExtractResourceResult: true,
		},
		Update: &yamlUpdateConfig{
			ReadModifyUpdate: true,
		},
		Response: &yamlResponse{
			IDField: "id",
		},
		Output: &yamlOutputConfig{
			Format: "table",
		},
		Arguments: yamlArguments{
			Params: []yamlArgument{
				{
					ArgName: "arg",
					Spec: []yamlArgSpec{
						{APIField: "s"},
					},
					Choices: []yamlChoice{
						{ArgValue: "av", EnumValue: "ev", HelpText: "ch"},
					},
					ResourceSpec: &yamlResourceSpec{
						Name:       "n",
						PluralName: "pn",
						Collection: "c",
						Attributes: []yamlAttribute{
							{AttributeName: "an"},
						},
						DisableAutoCompleters: true,
					},
				},
			},
		},
	}
	if diff := cmp.Diff(want, got); diff != "" {
		t.Errorf("mismatch (-want +got):\n%s", diff)
	}
}
