# NOTE: This file is autogenerated and should not be edited by hand.
"""Manage Standard Resource location resources."""

from googlecloudsdk.calliope import base


@base.ReleaseTracks(base.ReleaseTrack.GA)
@base.Autogenerated
@base.Hidden
class LocationsGa(base.Group):
  """Manage Standard Resource location resources."""
